[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:227 Starting new HTTP connection (1): 127.0.0.1:9981
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:452 http://127.0.0.1:9981 "POST http://localhost/zentaopms/www/api.php/v1/tokens HTTP/1.1" 400 150
[32mINFO    [0m root:apiRequerts.py:32 ----------------------------------------------------------------------------------------------------
[32mINFO    [0m root:apiRequerts.py:33 [  api name       ]: tokens
[32mINFO    [0m root:apiRequerts.py:34 [  request url    ]: http://localhost/zentaopms/www/api.php/v1/tokens
[32mINFO    [0m root:apiRequerts.py:35 [  method         ]: POST
[32mINFO    [0m root:apiRequerts.py:36 [  status code    ]: 400
[32mINFO    [0m root:apiRequerts.py:37 [  time total     ]: 0.054868
[32mINFO    [0m root:apiRequerts.py:40 [  response json  ]: {'error': '登录失败，请检查您的用户名或密码是否填写正确。'}
[32mINFO    [0m root:apiRequerts.py:43 ----------------------------------------------------------------------------------------------------